name: Workload Identity Federation
on:
  push:
    branches:
    - feature/pradeep
  workflow_dispatch:
jobs:
  get-secrets:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/132917503746/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
          service_account: 'github-actions@exam-preparation-300390.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: gcloud
        name: Access Secret Details
        run: |
          gcloud secrets versions access latest --secret=github-action
